[versions]
agp = "8.9.1"
okhttp = "4.12.0"
glide = "4.16.0"
junit = "4.13.2"
androidx-test-runner = "1.6.2"
espresso = "3.6.1"
androidx-core = "1.13.1"
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.1.4"
material = "1.12.0"

[libraries]
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }